# src/main/resources/application.yml

passwords:
  library: "341213452"
  homeroom: "10111" 
  "1fstairs": "dayandnight"
  teachersroom: "912534768"
  artroom: "052"
  gym2f: "사월의 반복"
  stairs2f: "5402"
  englishroom: "past"
  scienceroom: "tale"



