# src/main/resources/application.yml
passwords:
  map:
    library:       "341213452"
    homeroom:      "10111"
    "1fstairs":    "dayandnight"
    teachersroom:  "912534768"
    artroom:       "052"
    gym2f:         "사월의 반복"
    stairs2f:      "5402"
    englishroom:   "past"
    scienceroom:   "tale"
    powersupplyroom: "Fe"
    allergy: "30"
    radiation: "MMWRAS"
    intensive: "live project april millennium"
    filmingroom: "6489"
    rooftop: "9801"
    storage: "JUST ONE PAIR"